[app]
env = "dev"

[database]
host = "127.0.0.1"
port = 5432
name = "aisecurity"
user = "aisecurity"
password = "aisecurity"

[redis]
host = "127.0.0.1"
port = 6379
db = 0

[celery]
broker_db = 0
result_db = 1

[web]
next_public_api_base_url = "http://127.0.0.1:8000"
